version: "3.9"

services:
  database: 
    image: postgres
    container_name: pentagrama_db
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_DB=operational_control
      - POSTGRES_PASSWORD=pentpass
    volumes:
      - pgdata:/data/postgres

volumes: 
  pgdata: 